### PR TITLE
vue-component: avoid finding and replacing ‘export default’

### LINKED ISSUE #165: vue-coffee doesn’t build exports properly
Steps to reproduce:

```sh
git clone git@github.com:Akryum/meteor-vue2-example.git # 71830c0
meteor npm install
meteor update # Updates to 1.4.4.1, akyrum package versions as of 2017-04-24
```
Edit `App.vue` to move `Session.setDefault("counter", 0);` into `beforeCreate`, per [meteor-vue2-example#9](https://github.com/Akryum/meteor-vue2-example/issues/9):

```js
export default {
  beforeCreate() {
    Session.setDefault("counter", 0);
  },
  data() {
```

Start up the app.

```sh
meteor
```

It works. Stop the app.

Edit `App.vue` again, and change the `script` block to this:

```vue
<script lang="coffee">
import Chat from './Chat.vue'
import Test from './Test.vue'

import {Session} from 'meteor/session'

labels = ['Click me!', 'Click me again!', 'Here! Click here!', 'Again! Again!',
'Don\'t click me! No, I\'m just kidding. You can.', 'You like that?',
'Can you stratch me in the back please?', 'You are soooo nice! Click!',
'Hmmmm...', 'You know, you are wasting time clicking me.',
'No really, you can click me as much as you want.', 'Click me to level up!'];

export default {
  beforeCreate: ->
    Session.setDefault 'counter', 0
    return

  data: ->
    {
      buttonLabel: 'Click me!'
      count: 0
      user: null
    }

  meteor:
    data:
      count: ->
        Session.get 'counter'
      user: ->
        Meteor.user()

  methods:
    addOne: ->
      Session.set 'counter', @count + 1
      @buttonLabel = labels[Math.round(Math.random() * (labels.length - 1))]
      return

  components:
    Chat: Chat
    Test: Test

  metaInfo:
    title: 'Meteor + Vue'
}
</script>
```

Add `vue-coffee` and start the app again:

```sh
meteor add akryum:vue-coffee # Adds 0.0.4
meteor
```

Observe a flood of errors in the browser console:

image

If you revert back to the JavaScript version of the `script` block, but just change `export default` to `exports.default =`, you get the same errors in the console.

What extra processing is happening to `export default` for JavaScript code blocks, that isn’t happening to CommonJS `exports.default =` code blocks as produced by `vue-coffee`?

### PR DESCRIPTION
**Pull request by GeoffreyBooth**
Fixes #165, at least for projects that use `vue-component` (and not the `vue-router` or `vue-router2` Meteor packages, which aren’t used by [vue-meteor-demo](https://github.com/meteor-vue/vue-meteor-demo); I guess the recommended practice now is to use the NPM `vue-router` and not those Meteor packages?).

This PR uses proper module syntax to return modules’ scripts as the scripts for those components. Previously, `vue-component` was doing a find-and-replace on the source code for those components’ scripts, replacing `export default` with `return` before compiling the code. This is unsafe, to say the least, and also incompatible with any code that has already passed through Babel before reaching `vue-component` (such as code processed by `vue-coffee`). Now an extra line is appended to the bottom of the script, with code like:

```js
return require('/src/imports/ui/GoogleMap.vue').default;
```
This is backward-compatible with the workaround for `vue-coffee` mentioned in #165, where `return` was used at the top in place of `export default`; that still works, though now we can follow recommended Vue style and use `export default` instead. CommonJS syntax (`exports.default =`) also works.

### CODE REVIEW

File: packages/vue-component/plugin/tag-handler.js [hunk 1]
```diff
@@ -160,7 +160,7 @@ VueComponentTagHandler = class VueComponentTagHandler {
       }
 
       // Export
-      script = script.replace(jsExportDefaultReg, 'return');
+      script += `\nreturn require('${this.inputFile.getDisplayPath()}').default;`
```
Comment (mitar) [inline packages/vue-component/plugin/tag-handler.js]: Ingenious!!!

On the other hand, this makes it synchronous? So no on demand loading? Or is this done at some other level?

Comment (GeoffreyBooth) [inline packages/vue-component/plugin/tag-handler.js]: I’m not sure I understand your question. The `require` call only runs client-side (which is counterintuitive, I know).

**Comment by GeoffreyBooth** [comment]
To test this:
1. Check out https://github.com/meteor-vue/vue-meteor-demo/pull/13 into a new folder (which I’ll call `vue-meteor-demo`).
1. Check out https://github.com/meteor-vue/vue-meteor/pull/244 (this PR).
1. Copy the `vue-component` folder from this PR into `vue-meteor-demo/packages`. That project should already be set to use the version of `vue-component` from this PR.
1. In `vue-meteor-demo`, run `meteor`.

See also #243, which isn’t related to this bug/fix but works well with it. You can test that PR using the same method above (copying that PR’s `vue-coffee` folder into `vue-meteor-demo/packages/vue-coffee` and updating the version in `vue-meteor-demo/.meteor/versions`).

File: packages/vue-component/plugin/tag-handler.js (hunk 1 above)
Comment (mitar) [inline packages/vue-component/plugin/tag-handler.js]: Sorry, I didn't explain well. I am asking if this influences dynamic imports on the client. Dynamic imports return promises, but here we are loading this in sync. But probably one can then dynamically load the whole vue component?

**Comment by mitar** [comment]
How does this interact with Vue rendering on the server for components done in CoffeeScript? Does it matter? I have not yet tried it so not sure.

**Comment by GeoffreyBooth** [comment]
It seems to work as far as I can tell. If you follow the instructions in my previous comment, going to `localhost:3000` and navigating to `/map` works, as does opening a tab straight at `localhost:3000/map`. Does that prove that SSR works?

File: packages/vue-component/plugin/tag-handler.js (hunk 1 above)
Comment (GeoffreyBooth) [inline packages/vue-component/plugin/tag-handler.js]: Well previously the code was just `return { … }`, so I think this is no different than the current behavior. I don’t think dynamic imports are currently supported with `vue-component`.

Comment (Akryum) [inline packages/vue-component/plugin/tag-handler.js]: Dynamic imports should work. 😄

Comment (GeoffreyBooth) [inline packages/vue-component/plugin/tag-handler.js]: So @Akryum does this look okay to merge in?
